services:
  - type: web
    name: file-forge-toolkit
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr \
                         libtesseract-dev \
                         libleptonica-dev \
                         poppler-utils \
                         python3-pip \
                         python3-dev \
                         build-essential \
                         libssl-dev \
                         libffi-dev 
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: true
    aptPackages:
      - tesseract-ocr
      - libtesseract-dev
      - libleptonica-dev
      - poppler-utils
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
