services:
  - type: web
    name: file-forge-toolkit
    env: docker
    region: singapore  # Choose your preferred region
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
      - key: UPLOAD_FOLDER
        value: /app/uploads
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
    healthCheckPath: /health
    autoDeploy: true
