services:
  - type: web
    name: file-forge-toolkit
    env: python
    region: singapore  # Choose your preferred region
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr \
                         libtesseract-dev \
                         libleptonica-dev \
                         poppler-utils \
                         python3-pip \
                         python3-dev \
                         build-essential \
                         libssl-dev \
                         libffi-dev \
                         libmagic1
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: true
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: TESSERACT_CMD
        value: /usr/bin/tesseract
    aptPackages:
      - tesseract-ocr
      - libtesseract-dev
      - libleptonica-dev
      - poppler-utils
      - python3-pip
      - python3-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - libmagic1
    healthCheckPath: /health
    autoDeploy: true
